dist: xenial
language: python

python:
  - 3.6
  - 3.7

before_install:
  - pip freeze | xargs pip uninstall -y
  - pip install poetry tox-travis

script:
  - tox

notifications:
  email:
    on_success: never
    on_failure: change
