[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


[tool.poetry]
name = "pytest_mimesis"
version = "1.0.0"
description = "Mimesis integration with the pytest test runner"

license = "MIT"

authors = [
  "Nikita Sobolev <mail@sobolevn.me>",
  "Líkið Geimfari <likid.geimfari@gmail.com>",
  "Kevin Schellenberg"
]

readme = 'README.md'

repository = "https://github.com/mimesis-lab/pytest-mimesis"
homepage = "https://github.com/mimesis-lab/pytest-mimesis"

keywords = [
  "mimesis",
  "pytest",
  "testing",
  "fixtures",
  "fake data",
  "faker",
  "factory",
  "tests"
]


[tool.poetry.plugins.pytest11]
mimesis = "pytest_mimesis"


[tool.poetry.dependencies]
python = "^3.6"
pytest = ">=4.2"
mimesis = "^3.1"


[tool.poetry.dev-dependencies]
pytest-cov = "^2.6"
pytest-randomly = "^2.1"
flake8-pytest = "^1.3"
wemake-python-styleguide = "^0.8"
safety = "^1.8"
